name: Bug Report | 错误报告
description: Please describe in detail the problems you encountered in the process of using. | 请详细描述您使用过程中遇到的问题。
title: "[Bug]Some problem..."
labels: ["bug | 错误"]

body:
  - type: markdown
    attributes:
      value: |
        ***Please answer these questions before you submit a bug. | 请在您提交 bug 之前，回答以下这些问题。***

  - type: textarea
    attributes:
      label: 1. Your usage scenarios? | 您使用的场景？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 2. What did you do? | 您做了什么操作？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 3. What are your problems? | 您遇到了什么问题？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 4. What is your expected outcome? | 您期望的结果是怎样的？
    validations:
      required: true
